project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "NSIDC Data Cookbook"

  sidebar:
    title: "NSIDC Data Cookbook"
    logo: https://nsidc.org/themes/custom/nsidc/logo.svg
    pinned: true
    align: center
    tools: 
#      - icon: globe
#        href: https://nasa-openscapes.github.io
#        text: "NASA-Openscapes website"
      - icon: github
        href: https://github.com/nsidc/NSIDC-Data-Cookbook
        text: "NSIDC Data Cookbook repo"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Our Cookbook"
        href: nsidc-data-cookbook/our-cookbook.qmd
      - text: "Tools we use"
        href: tools-we-use.qmd
      - text: "Data Structures - types of data"
        href: reference-guides/data-structures.qmd
      - text: "Dataset search and discovery"
        href: reference-guides/dataset-search-and-discovery.qmd
      - text: "Common NSIDC file formats"
        href: reference-guides/nsidc-file-formats.qmd
      - text: "NSIDC map projections and grids"
        href: nsidc-data-cookbook/reference-guides/projections.qmd
      - text: "Plotting NSIDC Data"
        href: nsidc-data-cookbook/reference-guides/plotting-data.qmd
      - text: "Datasets"
        href: nsidc-data-cookbook/reference-guides/datasets.qmd
      - text: "What is an API?"
      - text: "NASA collections and granules"
      - section: "How do I..."
        href: nsidc-data-cookbook/how-to-guides/overview.qmd
        contents:
          - section: "reproject data?"
          - section: "work with NetCDF files?"
            contents:
            - text: "get the bounding box of a netcdf file"
              href: nsidc-data-cookbook/how-to-guides/netcdf_cf.qmd
            - text: "get the latitude and longitudes for grid cells"
              href: nsidc-data-cookbook/how-to-guides/get_latitude_and_longitude.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto

execute:
  freeze: auto
